### ISSUE TITLE
Grafana Dashboard

### ISSUE THREAD

**Issue by aldrinmagno** [engesin/Jitsi-Prometheus-Exporter#10]
Hello,

I manage to install Jitsi-Prometheus-Exporter properly but I'm having a hard time with Grafana itself. Can you please share your dashboard if possible please.

Thanks,

**Comment by engesin** [comment]
hi,

sample dashboard is at [dashboard](https://github.com/engesin/Jitsi-Prometheus-Exporter/blob/master/dashboards/dashboard.json) already :)
