### ISSUE TITLE
empty metrics

### ISSUE THREAD

**Issue by krakazyabra** [engesin/Jitsi-Prometheus-Exporter#4]
Hi! I'm running Jitsi in HA mode, one container per one process. That's why I have multiple containers with jicofo and jvb. I decided to run exporter as sideContainer. In this case I use local addresses for services. 
So, in each container exporter sees metrics of it's own process (f.e. in jvb container exporter gives me metrics only of jvb, metrics for jicofo in this container are _null_ (no value for metric)). 
Can you modify exporter in such way: if there are no values for metric - do not show this metrics.

**Comment by engesin** [comment]
Hi,

Output of the jpe is compatible with Prometheus so not showing empty metric is unexpected input for Prometheus.

Solution of your problem is filtering that metrics at grafana. You can set “null as zero” and write query as some_metric > 0

Briefly, you need to fix that problem at grafana.

**Comment by krakazyabra** [comment]
Thanks
