### ISSUE TITLE
Error: Unable to access jarfile ./jpe-0.0.1-SNAPSHOT.jar

### ISSUE THREAD

**Issue by anaisthrl** [engesin/Jitsi-Prometheus-Exporter#5]
Hi! I use Jitsi on localhost and I want to suppervise this server with your "Jitsi-Prometheus-Exporter'. 
I clone your repository in my Documents and I try this command in my WSL2 :
/usr/bin/java -DCONFIG_HOME=./conf -jar ./jpe-0.0.1-SNAPSHOT.jar

I have this error : "Error: Unable to access jarfile ./jpe-0.0.1-SNAPSHOT.jar"

Can you help me ? It's my first try for exporter in java language and I don't now where I must clone and how run my exporter...

Sorry for my approximatly english. 

I hope an answer... :D

**Comment by engesin** [comment]
Hi,

I update readme. You can check again.
