### ISSUE TITLE
installation guide

### ISSUE THREAD

**Issue by shankar-bavan** [engesin/Jitsi-Prometheus-Exporter#7]
I'm not clear with installation step. Do we need to manually download and install?

**Comment by apit** [comment]
yes, you need to download this repo tarball, extract it, cd into it, and run step no. 2 to build it . 
[edit] alternatively if you have docker, you can `docker build -t engesin/jpe .` and `docker run -p 6071:6071 engesin/jpe`

**Comment by shankar-bavan** [comment]
@apit Thank you. I got 2 more questions. I don't have docker. I use ubuntu server with nginx
1. Is there any specific folder to install ?
2. Should I need to configure nginx config for this? I installed jitsi meet on subsdomain.domain.com . can I use different subdomain for this?

**Comment by apit** [comment]
you dont have to use nginx. you setup prometheus to consume from this app configured host:port, anywhere it run from. you also need to create systemd  service definition (docker run --restart=always is simpler though).

edit: are you familiar with prometheus exporter?

**Comment by shankar-bavan** [comment]
> you dont have to use nginx. you setup prometheus to consume from this app configured host:port, anywhere it run from. you also need to create systemd service definition (docker run --restart=always is simpler though).
> 
> edit: are you familiar with prometheus exporter?

@apit Thank you. 
I'm not familiar with prometheus exporter. I found this on jitsi forum and trying to install
