### ISSUE TITLE
[BUG?] Error in ENTRYPOINT line in Dockerfile

### ISSUE THREAD

**Issue by pandel** [engesin/Jitsi-Prometheus-Exporter#9]
Hi!

In line https://github.com/engesin/Jitsi-Prometheus-Exporter/blob/f1281150158e2c1e680e38eac2780e0d10d8b502/Dockerfile#L15 seems to be an error (missing equal sign).

It should be like

`ENTRYPOINT ["java","-d64","-DCONFIG_HOME=./conf", "-jar", "./jpe-0.0.5-SNAPSHOT.jar"] `

Regards,
Holger

**Comment by engesin** [comment]
you are right. fixed.
